---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/f5_credentials.yml

  tasks:

  - name: CREATE POOL
    bigip_pool:
      server: "{{ ansible_host }}"
      user: "{{ F5_USERNAME }}"
      password: "{{ F5_PASSWORD }}"
      server_port: "8443"
      name: "http_pool"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
      validate_certs: "no"
