---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/f5_credentials.yml

  tasks:

  - name: CREATE NODES
    bigip_node:
      server: "{{ ansible_host }}"
      user: "{{ F5_USERNAME }}"
      password: "{{ F5_PASSWORD }}"
      server_port: "8443"
      host: "{{hostvars[item].ansible_host}}"
      name: "{{hostvars[item].inventory_hostname}}"
      validate_certs: "no"
    loop: "{{ groups['webservers'] }}"
