---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/f5_credentials.yml
  vars:
    pool_name: http_pool

  tasks:

  - name: CREATE POOL
    bigip_pool:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USERNAME }}"
        password: "{{ F5_PASSWORD }}"
        server_port: "8443"
        validate_certs: "no"
      name: "{{ pool_name }}"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
